name: Black Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black-check:
    name: Check code format with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up latest stable Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black check
        run: black --check .
