name: Flake8 + Mypy + Runtime Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-typecheck-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure flake8 and mypy are installed even if missing in requirements.txt
          pip install flake8 mypy

      - name: Run flake8
        run: flake8 .

      - name: Run mypy (type checking)
        run: mypy .

      - name: Run main.py (runtime test)
        run: python app.py